Repository poanetwork/tokenbridge-contracts, pull requests merged in 2018-08, with the labels that each got.

#57 Double spending fix
  contracts/libraries/Message.sol
  contracts/upgradeable_contracts/BasicForeignBridge.sol
  test/erc_to_erc/foreign_bridge.test.js
  test/erc_to_erc/home_bridge.test.js
  test/helpers/helpers.js
  test/native_to_erc/foreign_bridge_test.js
  test/native_to_erc/home_bridge_test.js
Labels: in progress

#66 Infer deployment address from private key
  deploy/.env.example
  deploy/README.md
  deploy/deploy.js
  deploy/src/deploymentUtils.js
  deploy/src/erc_to_erc/foreign.js
  deploy/src/erc_to_erc/home.js
  deploy/src/native_to_erc/foreign.js
  deploy/src/native_to_erc/home.js
  deploy/src/web3.js
Labels: in progress

#68 Add requiredMessageLength method to BasicHomeBridge contract
  contracts/libraries/Message.sol
  contracts/upgradeable_contracts/BasicHomeBridge.sol
  test/erc_to_erc/home_bridge.test.js
  test/native_to_erc/home_bridge_test.js
Labels: in progress, review

#69 Allow using the deploy script from another directory
  deploy/deploy.js
Labels: in progress, review

#71 Fix an issue when receipt is returning blockNumber null; add name, symbol, decimals to erc677
  contracts/upgradeable_contracts/erc20_to_erc20/ForeignBridgeErcToErc.sol
  deploy/.env.example
  deploy/README.md
  deploy/src/deploymentUtils.js
  deploy/src/erc_to_erc/foreign.js
  deploy/src/erc_to_erc/home.js
  deploy/src/native_to_erc/foreign.js
  deploy/src/native_to_erc/home.js
  test/erc_to_erc/foreign_bridge.test.js
Labels: review
